export type JournalPost = {
  slug: string;
  title: string;
  excerpt: string;
  category: "Styling" | "Care Tips" | "Silver Knowledge";
  image: string;
  date: string;
  readTime: string;
  content: { type: "p" | "h2" | "h3" | "img" | "list"; value: string | string[] }[];
};

export const journalPosts: JournalPost[] = [
  {
    slug: "how-to-style-silver-jewellery",
    title: "How to Style Silver Jewellery for Every Occasion",
    excerpt: "From boardrooms to brunches — learn how to wear silver with confidence. Layering, stacking, and pairing tips from our design team.",
    category: "Styling",
    image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=1200&h=600&fit=crop",
    date: "May 2026",
    readTime: "5 min",
    content: [
      { type: "p", value: "Silver jewellery is one of the most versatile accessories in your wardrobe. Unlike gold, which can sometimes feel too formal, silver moves effortlessly between casual and dressy — making it the perfect everyday companion." },
      { type: "h2", value: "For the Office" },
      { type: "p", value: "Keep it minimal and intentional. A single pair of polished hoops or a delicate pendant necklace adds sophistication without distraction. Avoid chunky statement pieces — instead, opt for clean lines and geometric shapes that complement professional attire." },
      { type: "p", value: "Our Double Band Oval Hoops are a favourite among working professionals. They frame the face elegantly and pair beautifully with both blazers and silk blouses." },
      { type: "h2", value: "For Brunch & Casual Outings" },
      { type: "p", value: "This is where you can play. Layer 2-3 necklaces of different lengths, stack rings on multiple fingers, or mix textures — polished with matte, smooth with textured. The key is to look effortless, not overdone." },
      { type: "list", value: ["Start with a choker or short chain as your base", "Add a pendant necklace 2-3 inches longer", "Finish with a longer chain if you want drama", "Keep earrings simple when necklaces are layered"] },
      { type: "h2", value: "For Evening & Special Occasions" },
      { type: "p", value: "Silver with cubic zirconia or gemstones elevates any evening look. A statement necklace set like our Floral Halo Solitaire paired with matching earrings creates a cohesive, luxurious appearance without the gold price tag." },
      { type: "p", value: "Pro tip: Silver photographs beautifully under artificial lighting — it catches and reflects light in ways that look stunning in photos. Perfect for weddings, parties, and celebrations." },
      { type: "h2", value: "The Golden Rule" },
      { type: "p", value: "There's only one rule in jewellery styling: wear what makes you feel confident. Rules about matching metals or limiting pieces are outdated. If it makes you smile when you look in the mirror, you're doing it right." },
    ],
  },
  {
    slug: "silver-care-101",
    title: "Silver Care 101: Keep Your Pieces Shining for Years",
    excerpt: "Sterling silver tarnishes — it's natural chemistry, not a defect. Here's everything you need to know about cleaning, storing, and maintaining your jewellery.",
    category: "Care Tips",
    image: "https://images.unsplash.com/photo-1617038220319-276d3cfab638?w=1200&h=600&fit=crop",
    date: "May 2026",
    readTime: "4 min",
    content: [
      { type: "p", value: "Let's address the elephant in the room: yes, sterling silver tarnishes. It's not a defect — it's chemistry. When silver reacts with sulphur compounds in the air, it forms a dark layer called silver sulphide. But with proper care, your pieces will maintain their brilliance for decades." },
      { type: "h2", value: "Daily Care Habits" },
      { type: "list", value: ["Put jewellery on last — after perfume, lotion, and hairspray", "Remove before swimming, showering, or exercising", "Wipe with a soft cloth after each wear to remove oils and moisture", "The more you wear silver, the less it tarnishes (your skin's natural oils actually help)"] },
      { type: "h2", value: "Cleaning Methods" },
      { type: "h3", value: "Method 1: Gentle Polish (Weekly)" },
      { type: "p", value: "Use a microfibre cloth or dedicated silver polishing cloth. Rub gently in straight lines (not circles) to avoid micro-scratches. This handles light tarnish and restores shine in seconds." },
      { type: "h3", value: "Method 2: Soap & Water (Monthly)" },
      { type: "p", value: "Mix a few drops of mild dish soap in warm water. Soak your jewellery for 5-10 minutes, then gently scrub with a soft toothbrush. Rinse thoroughly and pat dry completely — moisture left behind accelerates tarnishing." },
      { type: "h3", value: "Method 3: Baking Soda Paste (For Heavy Tarnish)" },
      { type: "p", value: "Mix 3 parts baking soda with 1 part water to form a paste. Apply with a soft cloth, rub gently, rinse, and dry. This is effective for pieces that haven't been worn in months." },
      { type: "h2", value: "Storage Tips" },
      { type: "list", value: ["Store each piece separately to prevent scratching", "Use anti-tarnish strips or silica gel packets in your jewellery box", "Keep in a cool, dry place away from direct sunlight", "Zip-lock bags work surprisingly well — squeeze out the air before sealing", "Never store silver in the bathroom (humidity accelerates tarnish)"] },
      { type: "h2", value: "What About Rhodium-Plated Silver?" },
      { type: "p", value: "All SILIQ pieces come with rhodium plating — a thin layer of rhodium (a platinum-group metal) that prevents tarnishing and adds extra shine. This plating lasts 1-3 years with regular wear. When it eventually wears off, you can get pieces re-plated at any jeweller for ₹200-500." },
    ],
  },
  {
    slug: "what-is-925-sterling-silver",
    title: "What is 925 Sterling Silver? The Complete Guide",
    excerpt: "The science behind the stamp. Why 92.5% silver is the international standard, how to verify authenticity, and why it matters for your jewellery.",
    category: "Silver Knowledge",
    image: "https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?w=1200&h=600&fit=crop",
    date: "Apr 2026",
    readTime: "6 min",
    content: [
      { type: "p", value: "When you see '925' stamped on jewellery, it means the piece is made of 92.5% pure silver and 7.5% other metals (usually copper). This isn't a compromise — it's engineering. Pure silver (99.9%) is too soft for jewellery. It would bend, scratch, and deform with daily wear. The 7.5% alloy gives sterling silver its strength while maintaining that beautiful white lustre." },
      { type: "h2", value: "Why Not Pure Silver?" },
      { type: "p", value: "Imagine wearing a ring made of butter. That's essentially what pure silver feels like to a jeweller — it's incredibly malleable. The copper alloy in 925 silver provides the structural integrity needed for intricate designs, secure stone settings, and everyday durability." },
      { type: "h2", value: "How to Verify Authenticity" },
      { type: "list", value: ["Look for the '925' stamp (also called a hallmark) — usually on the inside of rings, clasp of necklaces, or back of earrings", "In India, look for the BIS Hallmark — a triangle with 'BIS' inside, confirming government-certified purity", "Real silver is not magnetic — if a magnet sticks, it's fake", "The 'ice test' — silver conducts heat rapidly. Place an ice cube on the piece; it should melt noticeably faster than on other metals", "Price check — if 925 silver jewellery costs less than ₹500 for a substantial piece, question its authenticity"] },
      { type: "h2", value: "925 Silver vs Other Metals" },
      { type: "p", value: "Sterling silver offers 90% of the look of white gold or platinum at 10% of the price. It's hypoallergenic (safe for sensitive skin), durable enough for daily wear, and ages beautifully. The only maintenance required is occasional polishing — a small trade-off for accessible luxury." },
      { type: "h2", value: "The BIS Hallmark: India's Quality Guarantee" },
      { type: "p", value: "Every SILIQ piece carries the BIS (Bureau of Indian Standards) hallmark. This is India's official certification that the silver content has been independently tested and verified. It's your guarantee that you're getting exactly what you paid for — no plating over base metals, no misleading claims." },
      { type: "p", value: "The hallmark includes: the BIS logo, purity grade (925), assaying centre's mark, and the jeweller's identification mark. Together, these four elements create an unbreakable chain of accountability from manufacturer to your jewellery box." },
    ],
  },
  {
    slug: "ring-stacking-guide",
    title: "The Art of Ring Stacking: Rules, Tips & Combinations",
    excerpt: "Mixing textures, widths, and finishes. How to build a ring stack that looks intentional, personal, and effortlessly cool.",
    category: "Styling",
    image: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=1200&h=600&fit=crop",
    date: "Apr 2026",
    readTime: "4 min",
    content: [
      { type: "p", value: "Ring stacking is an art form — and like all art, it has principles (not rules). The goal is to create a combination that looks intentional and personal, not random or cluttered. Here's how to build a stack you'll love." },
      { type: "h2", value: "The Foundation: Start with One Statement" },
      { type: "p", value: "Every great stack has an anchor — one ring that draws the eye. This could be a solitaire, a wider band, or something with a gemstone. Place it on your ring finger or middle finger, then build around it." },
      { type: "h2", value: "The 3-5-7 Principle" },
      { type: "p", value: "Odd numbers look more natural than even. Aim for 3 rings on one hand for a subtle look, 5 for a statement, or 7 if you're going bold. Distribute them across fingers — not all on one." },
      { type: "list", value: ["Subtle (3 rings): Statement on ring finger + thin band on middle + midi ring on index", "Statement (5 rings): Add a pinky ring and a second thin band", "Bold (7 rings): Double up on 2-3 fingers with varying widths", "Always leave at least one finger bare — it creates visual breathing room"] },
      { type: "h2", value: "Mixing Textures & Widths" },
      { type: "p", value: "The secret to a professional-looking stack: vary the width. Alternate between thin bands (1-2mm) and wider pieces (4-6mm). Mix polished with matte, smooth with textured. This contrast is what makes a stack look curated rather than accidental." },
      { type: "h2", value: "Our Favourite Combinations" },
      { type: "list", value: ["The Classic Solitaire + Bezel Parallel Band + thin plain band", "Cosmic Pearl Charm Ring alone on index + Crystal Bridge + Honeycomb Solitaire on ring finger", "The Geometric Cross Ring + Unity Knot Dual Band on adjacent fingers"] },
      { type: "h2", value: "One Rule We Do Follow" },
      { type: "p", value: "Comfort. If a combination feels bulky, catches on things, or restricts movement — remove a piece. The best stack is one you forget you're wearing until someone compliments it." },
    ],
  },
  {
    slug: "silver-vs-gold-which-suits-you",
    title: "Silver vs Gold: Which Metal Flatters You Most?",
    excerpt: "Cool tones, warm tones, and neutral — a practical guide to choosing the metal that makes your skin glow.",
    category: "Styling",
    image: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=1200&h=600&fit=crop",
    date: "Mar 2026",
    readTime: "4 min",
    content: [
      { type: "p", value: "The age-old question: silver or gold? While personal preference always wins, there's actual science behind why certain metals look better on certain skin tones. Here's how to figure out your ideal match." },
      { type: "h2", value: "The Vein Test" },
      { type: "p", value: "Look at the veins on your inner wrist in natural light. If they appear blue or purple, you have cool undertones — silver will complement you beautifully. If they look green, you have warm undertones — gold is traditionally your match. If you see both, you're neutral — lucky you, everything works." },
      { type: "h2", value: "Why Silver Works for More People Than You Think" },
      { type: "p", value: "Here's what the traditional advice misses: silver is incredibly versatile. Its neutral, white-grey tone actually complements ALL skin tones — from the fairest to the deepest. It doesn't compete with your skin; it enhances it." },
      { type: "list", value: ["Fair skin: Silver creates elegant contrast without overwhelming", "Medium skin: Silver adds a cool, sophisticated brightness", "Olive skin: Silver's neutrality balances warm-green undertones beautifully", "Deep skin: Silver creates stunning, high-contrast drama", "Indian skin tones (warm-medium): Silver offers a modern alternative to traditional gold"] },
      { type: "h2", value: "The Modern Approach: Mix Metals" },
      { type: "p", value: "The 'rule' about not mixing metals is dead. Fashion-forward styling embraces silver and gold together. A silver necklace with gold rings, or silver earrings with a gold watch — these combinations look intentional and contemporary." },
      { type: "h2", value: "Silver's Practical Advantages" },
      { type: "list", value: ["60-80% more affordable than gold for the same design", "Matches more clothing colours (especially blacks, whites, blues, greys)", "Looks equally appropriate at 25 and 55", "Easier to maintain than gold (no karat concerns)", "More versatile for everyday wear without looking 'too much'"] },
      { type: "p", value: "At SILIQ, we believe silver is the thinking person's luxury. It's a choice that says 'I value design over display' — and that confidence is the most attractive accessory of all." },
    ],
  },
  {
    slug: "necklace-layering-tips",
    title: "Necklace Layering: 5 Principles That Always Work",
    excerpt: "Different lengths, varying textures, one focal point. Master the layered necklace look with these simple, repeatable principles.",
    category: "Styling",
    image: "https://images.unsplash.com/photo-1515562141589-67f0d569b6f5?w=1200&h=600&fit=crop",
    date: "Mar 2026",
    readTime: "4 min",
    content: [
      { type: "p", value: "Layered necklaces are the easiest way to elevate a simple outfit. But there's a fine line between 'effortlessly chic' and 'tangled mess.' These five principles will keep you on the right side." },
      { type: "h2", value: "Principle 1: Vary the Length" },
      { type: "p", value: "This is non-negotiable. Each necklace should sit at a distinctly different length — at least 2 inches apart. A choker (14-16\"), a mid-length (18-20\"), and a long piece (24-30\") creates the classic three-tier look." },
      { type: "h2", value: "Principle 2: One Focal Point" },
      { type: "p", value: "Only one necklace should be the 'star.' If your pendant is bold, keep the other chains simple. If you're layering multiple chains, make them all delicate. Two competing statement pieces create visual chaos." },
      { type: "h2", value: "Principle 3: Mix Chain Styles" },
      { type: "list", value: ["Pair a snake chain with a cable chain", "Mix a beaded strand with a smooth pendant chain", "Combine a thick chain with a delicate one", "Add a pearl strand for texture contrast"] },
      { type: "h2", value: "Principle 4: Consider Your Neckline" },
      { type: "p", value: "V-necks: Layer in a V-shape, with the longest piece following the neckline. Crew necks: Start with a choker that sits above the fabric. Off-shoulder: Go dramatic with longer pieces that fill the exposed space. High necks: Skip layering — one long pendant over the fabric works better." },
      { type: "h2", value: "Principle 5: The Anti-Tangle Trick" },
      { type: "p", value: "The biggest frustration with layered necklaces is tangling. Solutions: use chains of different weights (heavier chains tangle less with lighter ones), clasp all necklaces at the back at slightly different positions, or invest in a layering clasp that holds multiple chains on one closure." },
      { type: "p", value: "Our Stellar Beam and Pearl Loop Drop are designed to layer together — the chain weights and pendant sizes are calibrated to sit perfectly without tangling. Sometimes the best layering is the one that's been engineered for you." },
    ],
  },
];
